import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";
import Aurora from "../Aurora Background/Aurora"; // Adjust path if needed
import "./LegalPages.css";
import "../Aurora Background/Aurora.css";

export default function Disclaimer() {
  const navigate = useNavigate();

  return (
    <div className="legal-page">
      {/* Aurora Background */}
      <div className="legal-aurora-wrapper">
        <div className="aurora-container">
          <Aurora
            colorStops={["#ffcc00", "#ffffff", "#2969ff"]}
            blend={0.5}
            amplitude={1.0}
            speed={0.5}
          />
        </div>
      </div>
      <div className="legal-overlay" />

      <motion.div
        className="legal-content"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <button onClick={() => navigate(-1)} className="back-button">
          ← Back
        </button>

        <h1 className="legal-title">Disclaimer</h1>
        <span className="legal-date">Last Updated: January 2026</span>

        <h2 className="legal-section-title">
          Refunds & Handwriting Revision Policy
        </h2>
        <p className="legal-text">
          Handwrite provides one complimentary handwriting revision within 24
          hours of your handwriting font being activated on your account. If you
          feel that your handwriting output is not matching the style you
          intended, you may request a one-time correction without any additional
          page credits being deducted.
        </p>
        <p className="legal-text">
          Refunds for accidental or unintended credit purchases may be
          accommodated only if the purchased credits remain unused. To request a
          refund, users must contact us at our official support email within 48
          hours of the transaction. Refund eligibility will be reviewed on a
          case-by-case basis.
        </p>

        <h2 className="legal-section-title">General Information</h2>
        <p className="legal-text">
          The information provided by Handwrite ("we," "us," or "our") on our
          application is for general informational purposes only. All
          information on the Site and our mobile application is provided in good
          faith, however, we make no representation or warranty of any kind,
          express or implied, regarding the accuracy, adequacy, validity,
          reliability, availability, or completeness of any information.
        </p>

        <h2 className="legal-section-title">
          Academic Integrity & Responsible Use
        </h2>
        <p className="legal-text">
          The handwriting generation tools offered by Handwrite are meant for
          personal creativity, educational assistance, and note digitization. We
          do not encourage or support academic dishonesty, plagiarism, or
          misrepresentation of generated work as manually written material.
        </p>
        <p className="legal-text">
          Users are solely responsible for how they use the outputs generated by
          the platform.
        </p>

        <h2 className="legal-section-title">Not Professional Advice</h2>
        <p className="legal-text">
          The use of Handwrite to capture ideas, notes, or documents does not
          constitute professional legal, financial, or medical advice. Reliance
          on any information provided by this platform is solely at your own
          risk.
        </p>
      </motion.div>
    </div>
  );
}
